name: Release

on:
  push:
    branches:
      - main

permissions:
  contents: write
  issues: write
  pull-requests: write

jobs:
  release:
    name: Release
    runs-on: ubuntu-latest
    steps:
      - name: Checkout Repo
        uses: actions/checkout@v4
        with:
          fetch-depth: 0
      - uses: pnpm/action-setup@v4
        with:
          version: 8
      - uses: actions/setup-node@v4
        with:
          node-version: 20
          cache: "pnpm"

      - name: prebuild
        run: pnpm install --frozen-lockfile

      - name: build
        run: cd ./packages/json-to-python && pnpm build

      - name: create coverage report
        run: pnpm test:coverage
        working-directory: ./packages/json-to-python

      - name: Coveralls GitHub Action
        uses: coverallsapp/github-action@v2
        with:
          github-token: ${{ secrets.GITHUB_TOKEN }}

      - name: Filter publish files
        run: |
          cd ./packages/json-to-python
          find . ! \( -name 'dist' -o -name 'package.json' \) -mindepth 1 -maxdepth 1 -exec rm -r {} \;
          mv ../../README.md README.md
          mv ../../LICENSE LICENSE

      - name: Create Release Pull Request or Publish to npm
        id: changesets
        uses: changesets/action@v1
        with:
          version: pnpm update:version
          publish: pnpm release -r
          commit: "chore: release json-to-python"
          title: "chore: release json-to-python"
        env:
          GITHUB_TOKEN: ${{ secrets.GITHUB_TOKEN }}
          NPM_TOKEN: ${{ secrets.NPM_TOKEN }}
